### ISSUE TITLE
Criar a estrutura inicial da API

### ISSUE THREAD

**Issue by AnaJuliaMM** [AnaJuliaMM/library_manager#3]
- [x]  Inicializar Projeto Django `core`
- [x] Criar app `library`
- [x] Crias app `user`
- [x] Pastas `models`, `views` e `serializers`
- [x] `urls.py` dentro do app `user` e `library`
- [x] criar arquivo do `repository.py`
- [x] Pasta `templates`

**Comment by RafaelRodrigues44** [comment]
Aprovado Ana. Pode fazer. Rodei aqui sem erros.
